variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - lint
  - build
  - test
  - pages
  - publish
  - scan

include:
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/python-build.gitlab-ci.yml'
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/python-publish.gitlab-ci.yml'

python-publish-to-car:
  rules:
    - when: never

python-build-for-publication:
  rules:
    - when: never

build-patched-pytango:
  allow_failure: true
  stage: build
  image: $SKA_K8S_TOOLS_BUILD_DEPLOY
  tags:
    - ${SKA_DEFAULT_RUNNER}
  script:
    - make build-pytango950
    - make build-pytango951
  rules:
    - when: always
  artifacts:
    paths:
      - ./dist/
